---
name: Verify json schema

on:
  push:
    paths:
      - '.github/workflows/jsonschema.yaml'
      - 'catalog/**'
      - '*.schema.json'
  pull_request:
    paths:
      - '.github/workflows/jsonschema.yaml'
      - 'catalog/**'
      - '*.schema.json'

permissions: read-all # zizmor: ignore[excessive-permissions]

jobs:
  jsonschema_tests:
    name: Json Schema tests
    strategy:
      matrix:
        python-version: [3.11.3]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install check-jsonschema

      - name: Validate catalog.yaml
        run: |
          check-jsonschema --schemafile catalog.schema.json catalog/catalog.yaml

      - name: Validate pattern metadata files
        run: |
          for f in catalog/*/pattern.yaml; do
            echo "Validating ${f}..."
            check-jsonschema --schemafile pattern.schema.json "${f}"
          done
