---
name: Validate YAML

on:
  push:
    paths:
      - 'catalog/**'
  pull_request:
    paths:
      - 'catalog/**'

permissions: read-all  # zizmor: ignore[excessive-permissions]

jobs:
  yaml_lint:
    name: YAML lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6
        with:
          python-version: "3.11"

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files
        run: >-
          yamllint -s -d
          '{extends: default, rules: {line-length: disable, document-start: disable}}'
          catalog/
